### ISSUE TITLE
Option to exclude folders

### ISSUE THREAD

**Issue by Peluko** [johan-v-r/LibSassBuilder#1]
Hello. Great tool!

But I can't use it because it keeps compiling my node_modules folder. I've been looking into the source and it has no options to exclude folders.

Regards.

**Comment by johan-v-r** [comment]
Hi @Peluko , thanks 👍 

It will be difficult to give it configurable options as it's really just supposed to be a basic "install & run build task". Although I'm open to suggestions here?

That said, you make a good point in excluding some folders... I'm going to exclude the following folders by default:
- bin
- obj
- logs
- node_modules

This should be available in v1.2.0

**Comment by Peluko** [comment]
Well, I think that a simple 'libsassbuilder.config.json' on the project root folder could do as a simple and powerful configuration system.

**Comment by johan-v-r** [comment]
Yeah I like that idea. You're welcome to submit a PR as well if you can.

Have you tried the latest version yet?

**Comment by Peluko** [comment]
No, I haven't tested it yet. By now I have my own compiling/bundling workflow with webpack, I just came here for curiosity. Webpack is overkill for some projects, so eventually I'll give a try to this lib.

**Comment by johan-v-r** [comment]
Fair enough, I'm closing this in the meantime as the new versions should exclude those by default.
