### ISSUE TITLE
no compile when sass included file has changed

### ISSUE THREAD

**Issue by Michael-Anderlin** [johan-v-r/LibSassBuilder#21]
Hello,

I have a main styles.sass that includes other _xx.sass.
In the config I have set
```xml
    <SassFile Include="wwwroot/css/**/*.sass" Exclude="wwwroot/css/**/_*.sass" />
```
to exclude included sass  (which I think is also filtered in your code)
If any _xx.sass change but not the styles.sass, I got 
1>LibSass_DetermineBuildNeeded:
         Evaluating Sass files
         Sass hash New = 97c3fbaf0eec1cff794ebc9a9fbf65565b7b0dd0
         Sass hash Old = 97c3fbaf0eec1cff794ebc9a9fbf65565b7b0dd0
         Sass changed  = false

What should I do ?

Tx.

Regards,

Michael

**Comment by johan-v-r** [comment]
Hi there - try removing that `Exclude` attribute of yours so it looks like this:

```xml
<SassFile Include="wwwroot/css/**/*.sass" />
```

**Comment by Michael-Anderlin** [comment]
Hello,

That works, tx !

regards,

Michael
