### ISSUE TITLE
Include all *.razor.scss files, exclude specific others (app.razor.scss and all sass\*.scss files)

### ISSUE THREAD

**Issue by mormarijn** [johan-v-r/LibSassBuilder#22]
Hi.

I would like to include all *.razor.scss (under Pages and Shared) files to result in a *.css file, and I want to exclude app.razor.scss and all .scss files in my sass folder.

![image](https://user-images.githubusercontent.com/5318965/121884655-7707ba80-cd13-11eb-929f-e60be2b0f263.png)

My config is now as follows:

`<ItemGroup>
    <SassFile Include="**\*.razor.scss" Exclude="App.razor.scss, sass\*.scss" />
  </ItemGroup>`

However, this also results in an app.razor.css and sass\\*.css files. If I delete corresponding generated css files and run again, nothing gets generated until I update one of those excluded .scss files, and css files will be generated again which I do not want (explicitly stated to exclude).

Any idea how I have to setup my SassFile Include and Exclude filter in order to include all *.razor.scss files but exclude app.razor.scss and all .scss files in my sass folder?

I am looking forward to hearing from you soon. Thanks in advance and keep up the good work.

**Comment by johan-v-r** [comment]
Just another thought here... If you never want those files to compile to `*.css` (kinda like variable files) you could prefix them with an underscore. `**/_*` files are already excluded by default

**Comment by mormarijn** [comment]
> ```
> <PropertyGroup>
>   
>   <EnableDefaultSassItems>false</EnableDefaultSassItems>  
> </PropertyGroup>
> ```

Ah, that did the track, only thing with this is that those excluded *.scss files disappear from my cs proj (hidden so to say). Is that the way it's supposed to work?

Thanks for your help!

**Comment by johan-v-r** [comment]
Perhaps the file path or some config in your `.csproj` file?
Can you post your `.csproj` config or create a repro project?

**Comment by JelleHissink** [comment]
I find it a bit scary to use BuildingInsideVisualStudio, as this might result in a different build experience inside of VS and on the commandline. 
VS uses the includes to build the project view, but also runs msbuild within its context. So if you would use BuildingInsideVisualStudio I think the build would also include those items.

**Comment by johan-v-r** [comment]
Thanks for the feedback! I've left comments on the PR #28 
I'm gonna try to test & complete it this weekend, so any further suggestions/concerns please share on the PR.

**Comment by johan-v-r** [comment]
@mormarijn v1.6.4 should solve the hidden files issue.
