### ISSUE TITLE
macOS support

### ISSUE THREAD

**Issue by ChristianWeyer** [johan-v-r/LibSassBuilder#3]
Great lib! 

... and of course, the quest for also supporting, macOS is already here ;-)
Thanks.

**Comment by johan-v-r** [comment]
Hi @ChristianWeyer !

Haha sure thing, I've updated the tool with [LibSassHost.Native.osx-x64](https://www.nuget.org/packages/LibSassHost.Native.osx-x64/) which is released with v1.3.0

Unfortunately I don't have a mac to test, so if you could please and let me know..?

**Comment by ChristianWeyer** [comment]
Just tried it, with 1.3.0.
This is what I get when building the sample solution:

`/Users/christianweyer/.nuget/packages/libsassbuilder/1.3.0/build/LibSassBuilder.targets(5,5): Error MSB3073: The command "mono "/Users/christianweyer/.nuget/packages/libsassbuilder/1.3.0/build/../tool/LibSassBuilder.exe"" exited with code 2. (MSB3073) (BlazorWasmSass.Client)`

**Comment by johan-v-r** [comment]
Ah right think it might be the `LibSassBuilder.exe` very Windows specific - I've updated to rather run `dotnet LibSassBuilder.dll`

Please see if v1.4 fixes?

**Comment by ChristianWeyer** [comment]
This works - awesome, thanks :-)
