### ISSUE TITLE
Disable SCSS compilation inside docker

### ISSUE THREAD

**Issue by bezysoftware** [johan-v-r/LibSassBuilder#32]
Hi, I get the following error during my docker multi-build arm64 stage. 
```
There is no LibSassHost.Native.linux-* package for the arm64 processor architecture
```
Since I include the generated css files in the repo, I was thinking it's actually not needed to run the SCSS compilation during server build (done in Docker). Is there a way to do that?

**Comment by johan-v-r** [comment]
Hi - I _think_ it might skip the LSB task if there aren't any Sass files in the directory.
Perhaps try removing them before your server build then?

**Comment by JelleHissink** [comment]
Or put a Condition="" attribute on the package reference to LibSassBuilder?

**Comment by johan-v-r** [comment]
@bezysoftware closing this, please comment again for further discussion on this.
