### ISSUE TITLE
Not working in Jetbrains Rider

### ISSUE THREAD

**Issue by Martin-Andersen** [johan-v-r/LibSassBuilder#35]
Hi first thank for creating this project. Really appreciate not having node in my Blazor project.

LSB works when used with with VS 2019. But the build task is not running when I use Jetbrains Rider.
Do you know why?

A side note. Put this code in the readme file. Easy way to copy the output file to WWW

`<Target Name="CopyStyles" AfterTargets="AfterCompile">
    <Copy SourceFiles="$(MSBuildProjectDirectory)\Styles\styles.css" DestinationFolder="$(MSBuildProjectDirectory)\wwwroot\css" />
    <Message Importance="high" Text="Copying the minified build styles to WWWROOT" />
  </Target>`

**Comment by johan-v-r** [comment]
Hi there - Could you please post the error message and your version of Rider?

I tested it with Rider as part of #27 which worked fine then, unfortunately my trial has now expired.

**Comment by JsonTyler** [comment]
Hey thank you for the time you have put into this project, unfortunately I am getting an error while installing LibSassBuilder-Tool v2.0.0 in JetBrains Rider.

`Install failed (project: my.project.name, package: LibSassBuilder-Tool v2.0.0) Package 'LibSassBuilder-Tool 2.0.0' has a package type 'DotnetTool' that is not supported by project 'C:\my\projects\location\my_project.csproj'`

**Comment by johan-v-r** [comment]
@JsonTyler the `LibSassBuilder-Tool` package is a dotnet global tool. Use the `LibSassBuilder` package instead for project installations.

**Comment by johan-v-r** [comment]
@Martin-Andersen please comment again for further discussion.
