### ISSUE TITLE
Run manually via dotnet / console

### ISSUE THREAD

**Issue by braidenstiller** [johan-v-r/LibSassBuilder#5]
Is it possible to run the nuget package manually in the console outside of dotnet build? For example rebuilding the sass files while debugging?

**Comment by johan-v-r** [comment]
No not yet. I was thinking about making this into a global tool at some point which could do that.

In the meantime, see if [dotnet watch](https://docs.microsoft.com/en-us/aspnet/core/tutorials/dotnet-watch) could work for you? That's how I use it most of the time.

I add this to my `csproj`
```xml
<ItemGroup>
    <!-- extends watching group - https://docs.microsoft.com/en-us/aspnet/core/tutorials/dotnet-watch?view=aspnetcore-5.0#customize-files-list-to-watch -->
    <Watch Include="**\*.scss" Exclude="**\*.css" />
</ItemGroup>
```

Then run it with `dotnet watch run`

**Comment by johan-v-r** [comment]
I've published a global tool now as well. See [readme](https://github.com/johan-v-r/LibSassBuilder#net-global-tool) and please let me know if this works for you?

**Comment by braidenstiller** [comment]
Perfect. Thanks for the quick turnaround johan 👍
