### ISSUE TITLE
Do not override if only white space (or EOL) changes

### ISSUE THREAD

**Issue by JeanFTP** [johan-v-r/LibSassBuilder#51]
Using Git & Visual Studio, it happens often when changing branches that css files are re-generated even if only white space or end-of-line changes are found.
It is kind of anoying when you combine with git use, as it finds modified files when it is actalluy the same.
Is there a way to avoid this behavior? And if not, would it be possible to implement an option for this?

**Comment by johan-v-r** [comment]
Hi Jean - do you have any suggestions how that could work?

We already have a hash check to see if files were modified, and I believe whitespace/EOL would affect that as well. I think even MSBuild would recompile on whitespace changes in `.cs` files.

**Comment by JeanFTP** [comment]
Quite easy : 
Replace `result.CompiledContent == await File.ReadAllTextAsync(newFile))` with `RemoveEndOfLines(result.CompiledContent) == RemoveEndOfLines(await File.ReadAllTextAsync(newFile))`
And add:

```
        static string RemoveEndOfLines(string s)
            => string.Join("", string.Split(new[] { '\r' }, s, StringSplitOptions.RemoveEmptyEntries));
``` 

Needs to be tested, but this should work

**Comment by JeanFTP** [comment]
See https://github.com/johan-v-r/LibSassBuilder/pull/52

**Comment by JeanFTP** [comment]
@johan-v-r Would that be a reasonable change for you ?
On our side it is really a pain to have css changes every compilation when switching branches

**Comment by johan-v-r** [comment]
Looks good thanks for the PR! Will update shortly

**Comment by JeanFTP** [comment]
Great, however I believe you havean issue with the CI :)

**Comment by JeanFTP** [comment]
@johan-v-r
