### ISSUE TITLE
Plans for NET7 support

### ISSUE THREAD

**Issue by wihary** [johan-v-r/LibSassBuilder#53]
Hi @johan-v-r  !

First of all thanks for your lib ;)
As for the .Net 7 support event if it's still in preview, do you plan to migrate yourself ?

Could we create a 'preview' of  LibSassBuilder with NET7 support ?
If you want I can initiate a new PR for this.

Thanks !

**Comment by johan-v-r** [comment]
Hi @wihary - yes this will be upgraded when .NET 7 is released.

Don't think we really need the preview.. You can use this package in a .NET 7 project - LSB just needs .NET 6 installed on the machine as it executes _before_ your app actually runs.

**Comment by LeeRoyManea** [comment]
.NET 7 is out now. Please provide a version i can use for building my projects with CI CD & Docker.  The Containers from Microsont i use for .net core 7 dont provide .net core 6 SDK

**Comment by johan-v-r** [comment]
.NET 7 supported with v3 👍
